/* turbolite — SQLite VFS with compression, encryption, and S3 tiered storage.
 *
 * Auto-generated by cbindgen. Do not edit manually.
 * https://github.com/russellromney/turbolite
 */


#ifndef TURBOLITE_H
#define TURBOLITE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Option_CreateFnDestroy Option_CreateFnDestroy;

typedef struct Option_CreateFnFinal Option_CreateFnFinal;

typedef struct Option_CreateFnStep Option_CreateFnStep;

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Opaque database connection handle.
 */
typedef struct TurboliteDb TurboliteDb;
#endif

typedef void sqlite3;

typedef void sqlite3_context;

typedef void sqlite3_value;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Get the last error message, or NULL if no error occurred.
 *
 * The returned pointer is valid until the next turbolite_* call on this thread.
 */
const char *turbolite_last_error(void);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Get the turbolite version string. Always returns a valid pointer.
 */
const char *turbolite_version(void);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Register a local TurboliteVfs (page groups on disk, no S3).
 *
 * This is the recommended way to create a high-performance local SQLite VFS
 * with compressed page groups and manifest-based storage.
 *
 * # Parameters
 * - `name`: VFS name (e.g. `"turbolite"`). Must be unique.
 * - `cache_dir`: Directory where page groups and manifest are stored.
 * - `compression_level`: zstd level 1-22 (3 is a good default).
 *
 * # Returns
 * 0 on success, -1 on error. Call `turbolite_last_error()` for details.
 */
int turbolite_register_local(const char *name, const char *cache_dir, int compression_level);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Register a TurboliteVfs from a JSON configuration string.
 *
 * Unified entry point that supports both local and cloud modes. The JSON
 * object is deserialized into a `TurboliteConfig`. Unknown fields are ignored.
 *
 * # Minimal JSON (local mode)
 *
 * ```json
 * { "cache_dir": "/data/mydb" }
 * ```
 *
 * # Cloud mode
 *
 * ```json
 * {
 *   "storage_backend": { "S3": { "bucket": "my-bucket", "prefix": "db/" } },
 *   "cache_dir": "/tmp/cache"
 * }
 * ```
 *
 * # Parameters
 * - `name`: VFS name (e.g. `"turbolite"`). Must be unique.
 * - `config_json`: JSON string with configuration fields.
 *
 * # Returns
 * 0 on success, -1 on error. Call `turbolite_last_error()` for details.
 */
int turbolite_register(const char *name, const char *config_json);
#endif

#if (!defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Register an S3-backed cloud VFS.
 *
 * The VFS stores data in S3 with a local NVMe cache. Requires the `cloud`
 * feature at build time.
 *
 * # Parameters
 * - `name`: VFS name.
 * - `bucket`: S3 bucket name.
 * - `prefix`: S3 key prefix (e.g. `"databases/tenant-123"`).
 * - `cache_dir`: Local cache directory path.
 * - `endpoint_url`: Custom S3 endpoint (for MinIO/Tigris), or NULL for AWS default.
 * - `region`: AWS region, or NULL for `"auto"`.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_register_cloud(const char *name,
                             const char *bucket,
                             const char *prefix,
                             const char *cache_dir,
                             const char *endpoint_url,
                             const char *region);
#endif

#if (!defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Backward-compatible alias for `turbolite_register_cloud`.
 */
int turbolite_register_tiered(const char *name,
                              const char *bucket,
                              const char *prefix,
                              const char *cache_dir,
                              const char *endpoint_url,
                              const char *region);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Clear all VFS caches (shared file state, in-process locks).
 *
 * Call this when running fresh benchmarks or tests to ensure no stale state.
 */
void turbolite_clear_caches(void);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Invalidate cached state for a specific database file.
 *
 * Call after modifying a database file externally (e.g. after compaction).
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_invalidate_cache(const char *path);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Open a database using a previously registered VFS.
 *
 * # Parameters
 * - `path`: Database file path.
 * - `vfs_name`: Name of the VFS registered via `turbolite_register_*`.
 *
 * # Returns
 * Opaque handle on success, NULL on error. Must be closed with `turbolite_close`.
 */
struct TurboliteDb *turbolite_open(const char *path, const char *vfs_name);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Execute a SQL statement (DDL/DML) that returns no rows.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_exec(struct TurboliteDb *db, const char *sql);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Execute a SQL query and return results as a JSON array of objects.
 *
 * Example return: `[{"id":1,"name":"alice"},{"id":2,"name":"bob"}]`
 *
 * # Returns
 * Heap-allocated JSON string on success (caller must free with `turbolite_free_string`),
 * or NULL on error.
 */
char *turbolite_query_json(struct TurboliteDb *db, const char *sql);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Free a string returned by `turbolite_query_json`.
 */
void turbolite_free_string(char *s);
#endif

#if !defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Close a database connection opened with `turbolite_open`.
 */
void turbolite_close(struct TurboliteDb *db);
#endif

#if defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Called from C entry point (`sqlite3_turbolite_init` in ext_entry.c).
 * Returns 0 on success, 1 on error. Idempotent: second call is a no-op.
 *
 * Always registers "turbolite" (local TurboliteVfs).
 * If TURBOLITE_BUCKET is set, also registers "turbolite-s3" (tiered VFS).
 * Panics if TURBOLITE_BUCKET is set but tiered VFS creation fails.
 */
int turbolite_ext_register_vfs(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Clear cache. mode: 0 = all, 1 = data only, 2 = interior only (keeps interior + group 0).
 * Returns 0 on success, 1 if no tiered VFS.
 */
int32_t turbolite_bench_clear_cache(int32_t mode);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Reset S3 counters. Always returns 0; counters are now backend-impl
 * specific and not exposed through the generic trait.
 */
int32_t turbolite_bench_reset_s3(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Get S3 GET count. Returns 0: not surfaced through the generic
 * `StorageBackend` trait. Embedders that need per-backend metrics
 * hold a concrete `hadb_storage_s3::S3Storage` directly.
 */
int64_t turbolite_bench_s3_gets(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Get S3 GET bytes. Always 0; see above.
 */
int64_t turbolite_bench_s3_bytes(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Evict cached data for named trees. tree_names is a comma-separated C string.
 * Returns number of groups evicted, or -1 if no tiered VFS.
 */
int32_t turbolite_evict_tree(const char *tree_names);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && !defined(TURBOLITE_CLOUD))
int32_t turbolite_evict_tree(const char *_tree_names);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Return cache info as a JSON C string. Caller must treat as SQLITE_TRANSIENT.
 * Returns null if no tiered VFS.
 *
 * Uses a thread-local buffer to avoid allocation lifetime issues across FFI.
 */
const char *turbolite_cache_info(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Warm cache for a planned query. Runs EQP to extract trees, submits groups to prefetch.
 * Returns JSON C string with trees warmed and groups submitted. Null if no tiered VFS.
 * db must be a valid sqlite3 handle, sql must be a valid C string.
 */
const char *turbolite_warm(void *db, const char *sql);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && !defined(TURBOLITE_CLOUD))
const char *turbolite_warm(void *_db, const char *_sql);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Evict cached data for trees referenced by a SQL query. Runs EQP, extracts
 * tree names, evicts their groups. Returns groups evicted, or -1 if no VFS.
 */
int32_t turbolite_evict_query(void *db, const char *sql);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && !defined(TURBOLITE_CLOUD))
int32_t turbolite_evict_query(void *_db, const char *_sql);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Evict cached sub-chunks by tier. Accepts "data", "index", or "all".
 * Returns number of sub-chunks evicted, or -1 if no tiered VFS.
 */
int32_t turbolite_evict(const char *tier);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && !defined(TURBOLITE_CLOUD))
int32_t turbolite_evict(const char *_tier);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && !defined(TURBOLITE_CLOUD))
const char *turbolite_cache_info(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Full GC: list all S3 objects under prefix, delete orphans not in manifest.
 * Returns number of objects deleted, or -1 if no tiered VFS.
 */
int32_t turbolite_gc(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && defined(TURBOLITE_CLOUD))
/**
 * Compact B-tree groups: re-walk B-trees, repack groups with >30% dead space.
 * Returns JSON report string (caller must free), or null on error.
 */
const char *turbolite_compact(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && !defined(TURBOLITE_CLOUD))
const char *turbolite_compact(void);
#endif

#if (defined(TURBOLITE_LOADABLE_EXTENSION) && !defined(TURBOLITE_CLOUD))
int32_t turbolite_gc(void);
#endif

#if defined(TURBOLITE_LOADABLE_EXTENSION)
/**
 * Create and register a new local VFS with a custom name and cache directory.
 * Called from SQL: SELECT turbolite_register_vfs('name', '/path/to/cache_dir').
 * Each registered VFS gets its own manifest, cache, and page group state,
 * enabling multiple independent databases in the same process.
 * Returns 0 on success, 1 on error.
 */
int turbolite_ext_register_named_vfs(const char *name_ptr, const char *cache_dir_ptr);
#endif

/**
 * Run EQP on `sql` against `db` and push the planned accesses onto the
 * global plan queue. Invoked from `SQLITE_TRACE_STMT`.
 *
 * # Safety
 * `db` must be a valid sqlite3 handle. `sql` must be a valid C string.
 */
void turbolite_trace_push_plan(void *db, const char *sql);

/**
 * Signal query completion so the VFS runs between-query eviction on the
 * next read. Invoked from `SQLITE_TRACE_PROFILE`.
 */
void turbolite_trace_end_query(void);

/**
 * FFI entry point: `turbolite_config_set(key, value)`.
 *
 * Returns:
 *   0 — pushed successfully
 *   1 — validation failed (unknown key or bad value)
 *   2 — no active turbolite handle on this thread
 *
 * # Safety
 * `key` and `value` must be valid C strings.
 */
int turbolite_config_set(const char *key, const char *value);

/**
 * Clone an Arc to the current thread's top-of-stack handle queue, or
 * return NULL if no turbolite connection is active on this thread.
 *
 * The returned pointer owns one refcount; the caller must eventually
 * release it via [`turbolite_settings_queue_free`] — typically by
 * handing it to `sqlite3_create_function_v2` as `pApp` with
 * [`turbolite_settings_queue_free_cb`] as `xDestroy`.
 *
 * Used by `turbolite_install_config_functions` to snapshot the calling
 * connection's queue at install time.
 */
const void *turbolite_current_queue_clone(void);

/**
 * Drop one refcount on a queue pointer previously returned by
 * [`turbolite_current_queue_clone`]. NULL is a no-op.
 *
 * # Safety
 * `ptr` must be NULL or a pointer returned by
 * `turbolite_current_queue_clone` (not yet freed).
 */
void turbolite_settings_queue_free(const void *ptr);

/**
 * `xDestroy` callback signature wrapper for
 * `sqlite3_create_function_v2`. `void *` instead of `const void *` to
 * match SQLite's callback ABI.
 *
 * # Safety
 * `ptr` must be NULL or a pointer returned by
 * `turbolite_current_queue_clone` (not yet freed).
 */
void turbolite_settings_queue_free_cb(void *ptr);

/**
 * Push a `(key, value)` update into a specific queue pointer. Used by
 * the C shim's `turbolite_config_set_func` after pApp-capture.
 *
 * Returns:
 *   0 — pushed successfully
 *   1 — validation failed (unknown key / bad value) or null pointer
 *
 * # Safety
 * `queue_ptr` must be a live pointer returned by
 * `turbolite_current_queue_clone`. `key` / `value` must be valid C
 * strings.
 */
int turbolite_settings_queue_push(const void *queue_ptr, const char *key, const char *value);

extern int sqlite3_exec(sqlite3 *db,
                        const char *sql,
                        const void *callback,
                        const void *arg,
                        char **errmsg);

extern void sqlite3_free(void *ptr);

extern int sqlite3_create_function_v2(sqlite3 *db,
                                      const char *zFunctionName,
                                      int nArg,
                                      int eTextRep,
                                      void *pApp,
                                      struct Option_CreateFnStep xFunc,
                                      struct Option_CreateFnStep xStep,
                                      struct Option_CreateFnFinal xFinal,
                                      struct Option_CreateFnDestroy xDestroy);

extern void *sqlite3_user_data(sqlite3_context *ctx);

extern const char *sqlite3_value_text(sqlite3_value *value);

extern void sqlite3_result_error(sqlite3_context *ctx, const char *msg, int len);

extern void sqlite3_result_int(sqlite3_context *ctx, int val);

/**
 * Register the `turbolite_config_set(key, value)` SQL function on this
 * connection, capturing the calling connection's handle queue via
 * `sqlite3_create_function_v2`'s `pApp`.
 *
 * Returns:
 * - `SQLITE_OK` (0) on success
 * - A SQLite error code if the `PRAGMA schema_version` probe fails
 *   (connection isn't turbolite-backed)
 * - `SQLITE_MISUSE` if no turbolite handle is active on this thread
 *   after the probe
 *
 * # Safety
 * `db` must be a live `sqlite3*` handle.
 */
int turbolite_install_config_functions(sqlite3 *db);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TURBOLITE_H */
