FROM public.ecr.aws/lambda/provided:al2023
COPY target/lambda/tiered-bench/bootstrap /var/task/tiered-bench
COPY lambda-bootstrap.sh /var/runtime/bootstrap
RUN chmod +x /var/runtime/bootstrap /var/task/tiered-bench
CMD ["handler"]
