/* turbolite — SQLite VFS with compression, encryption, and S3 tiered storage.
 *
 * Auto-generated by cbindgen. Do not edit manually.
 * https://github.com/russellromney/turbolite
 */


#ifndef TURBOLITE_H
#define TURBOLITE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#if defined(TURBOLITE_TIERED)
/**
 * Minimum confidence to fire a prediction.
 */
#define CONFIDENCE_THRESHOLD 0.5
#endif

/**
 * Opaque database connection handle.
 */
typedef struct TurboliteDb TurboliteDb;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Get the last error message, or NULL if no error occurred.
 *
 * The returned pointer is valid until the next turbolite_* call on this thread.
 */
const char *turbolite_last_error(void);

/**
 * Get the turbolite version string. Always returns a valid pointer.
 */
const char *turbolite_version(void);

/**
 * Register a compressed VFS with SQLite.
 *
 * After registration, open databases with `sqlite3_open_v2(..., name)`.
 *
 * # Parameters
 * - `name`:  VFS name (e.g. `"turbolite"`). Must be unique.
 * - `base_dir`: Directory where database files are stored.
 * - `compression_level`: zstd level 1-22 (3 is a good default).
 *
 * # Returns
 * 0 on success, -1 on error. Call `turbolite_last_error()` for details.
 */
int turbolite_register_compressed(const char *name, const char *base_dir, int compression_level);

/**
 * Register a passthrough VFS (no compression, no encryption).
 *
 * Pages are stored in the VFS index format but without transformation.
 * Useful for benchmarking or data that doesn't benefit from compression.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_register_passthrough(const char *name, const char *base_dir);

#if defined(TURBOLITE_ENCRYPTION)
/**
 * Register an encrypted + compressed VFS.
 *
 * Pages are compressed with zstd then encrypted with AES-256-GCM.
 * Requires the `encryption` feature at build time.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_register_encrypted(const char *name,
                                 const char *base_dir,
                                 int compression_level,
                                 const char *password);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Register a tiered S3-backed VFS.
 *
 * The VFS stores data in S3 with a local NVMe cache. Requires the `tiered`
 * feature at build time.
 *
 * # Parameters
 * - `name`: VFS name.
 * - `bucket`: S3 bucket name.
 * - `prefix`: S3 key prefix (e.g. `"databases/tenant-123"`).
 * - `cache_dir`: Local cache directory path.
 * - `endpoint_url`: Custom S3 endpoint (for MinIO/Tigris), or NULL for AWS default.
 * - `region`: AWS region, or NULL for `"auto"`.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_register_tiered(const char *name,
                              const char *bucket,
                              const char *prefix,
                              const char *cache_dir,
                              const char *endpoint_url,
                              const char *region);
#endif

/**
 * Clear all VFS caches (shared file state, in-process locks).
 *
 * Call this when running fresh benchmarks or tests to ensure no stale state.
 */
void turbolite_clear_caches(void);

/**
 * Invalidate cached state for a specific database file.
 *
 * Call after modifying a database file externally (e.g. after compaction).
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_invalidate_cache(const char *path);

/**
 * Open a database using a previously registered VFS.
 *
 * # Parameters
 * - `path`: Database file path.
 * - `vfs_name`: Name of the VFS registered via `turbolite_register_*`.
 *
 * # Returns
 * Opaque handle on success, NULL on error. Must be closed with `turbolite_close`.
 */
struct TurboliteDb *turbolite_open(const char *path, const char *vfs_name);

/**
 * Execute a SQL statement (DDL/DML) that returns no rows.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_exec(struct TurboliteDb *db, const char *sql);

/**
 * Execute a SQL query and return results as a JSON array of objects.
 *
 * Example return: `[{"id":1,"name":"alice"},{"id":2,"name":"bob"}]`
 *
 * # Returns
 * Heap-allocated JSON string on success (caller must free with `turbolite_free_string`),
 * or NULL on error.
 */
char *turbolite_query_json(struct TurboliteDb *db, const char *sql);

/**
 * Free a string returned by `turbolite_query_json`.
 */
void turbolite_free_string(char *s);

/**
 * Close a database connection opened with `turbolite_open`.
 */
void turbolite_close(struct TurboliteDb *db);

/**
 * Called from C entry point (`sqlite3_turbolite_init` in ext_entry.c).
 * Returns 0 on success, 1 on error. Idempotent: second call is a no-op.
 *
 * Always registers "turbolite" (local compressed VFS).
 * If TURBOLITE_BUCKET is set, also registers "turbolite-s3" (tiered VFS).
 * Panics if TURBOLITE_BUCKET is set but tiered VFS creation fails.
 */
int turbolite_ext_register_vfs(void);

#if defined(TURBOLITE_TIERED)
/**
 * Clear cache. mode: 0 = all, 1 = data only, 2 = interior only (keeps interior + group 0).
 * Returns 0 on success, 1 if no tiered VFS.
 */
int32_t turbolite_bench_clear_cache(int32_t mode);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Reset S3 counters. Returns 0 on success.
 */
int32_t turbolite_bench_reset_s3(void);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Get S3 GET count since last reset.
 */
int64_t turbolite_bench_s3_gets(void);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Get S3 GET bytes since last reset.
 */
int64_t turbolite_bench_s3_bytes(void);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Evict cached data for named trees. tree_names is a comma-separated C string.
 * Returns number of groups evicted, or -1 if no tiered VFS.
 */
int32_t turbolite_evict_tree(const char *tree_names);
#endif

#if !defined(TURBOLITE_TIERED)
int32_t turbolite_evict_tree(const char *_tree_names);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Return cache info as a JSON C string. Caller must treat as SQLITE_TRANSIENT.
 * Returns null if no tiered VFS.
 *
 * Uses a thread-local buffer to avoid allocation lifetime issues across FFI.
 */
const char *turbolite_cache_info(void);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Warm cache for a planned query. Runs EQP to extract trees, submits groups to prefetch.
 * Returns JSON C string with trees warmed and groups submitted. Null if no tiered VFS.
 * db must be a valid sqlite3 handle, sql must be a valid C string.
 */
const char *turbolite_warm(void *db, const char *sql);
#endif

#if !defined(TURBOLITE_TIERED)
const char *turbolite_warm(void *_db, const char *_sql);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Evict cached sub-chunks by tier. Accepts "data", "index", or "all".
 * Returns number of sub-chunks evicted, or -1 if no tiered VFS.
 */
int32_t turbolite_evict(const char *tier);
#endif

#if !defined(TURBOLITE_TIERED)
int32_t turbolite_evict(const char *_tier);
#endif

#if !defined(TURBOLITE_TIERED)
const char *turbolite_cache_info(void);
#endif

#if defined(TURBOLITE_TIERED)
extern int32_t sqlite3_prepare_v2(void *db,
                                  const char *sql,
                                  int32_t nbyte,
                                  void **stmt,
                                  const char **tail);
#endif

#if defined(TURBOLITE_TIERED)
extern int32_t sqlite3_step(void *stmt);
#endif

#if defined(TURBOLITE_TIERED)
extern const char *sqlite3_column_text(void *stmt, int32_t col);
#endif

#if defined(TURBOLITE_TIERED)
extern int32_t sqlite3_finalize(void *stmt);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * FFI entry point called from C trace callback.
 * Runs EQP, parses, and pushes to global queue.
 *
 * # Safety
 * `db` must be a valid sqlite3 handle. `sql` must be a valid C string.
 */
void turbolite_trace_push_plan(void *db, const char *sql);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * FFI entry point called from C trace profile callback.
 * Signals query completion for between-query eviction.
 */
void turbolite_trace_end_query(void);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * FFI entry point: `turbolite_config_set(key, value)` SQL function.
 *
 * # Safety
 * `key` and `value` must be valid C strings.
 */
int32_t turbolite_config_set(const char *key, const char *value);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TURBOLITE_H */
