/* turbolite — SQLite VFS with compression, encryption, and S3 tiered storage.
 *
 * Auto-generated by cbindgen. Do not edit manually.
 * https://github.com/russellromney/turbolite
 */


#ifndef TURBOLITE_H
#define TURBOLITE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque database connection handle.
 */
typedef struct TurboliteDb TurboliteDb;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Get the last error message, or NULL if no error occurred.
 *
 * The returned pointer is valid until the next turbolite_* call on this thread.
 */
const char *turbolite_last_error(void);

/**
 * Get the turbolite version string. Always returns a valid pointer.
 */
const char *turbolite_version(void);

/**
 * Register a compressed VFS with SQLite.
 *
 * After registration, open databases with `sqlite3_open_v2(..., name)`.
 *
 * # Parameters
 * - `name`:  VFS name (e.g. `"turbolite"`). Must be unique.
 * - `base_dir`: Directory where database files are stored.
 * - `compression_level`: zstd level 1-22 (3 is a good default).
 *
 * # Returns
 * 0 on success, -1 on error. Call `turbolite_last_error()` for details.
 */
int turbolite_register_compressed(const char *name, const char *base_dir, int compression_level);

/**
 * Register a passthrough VFS (no compression, no encryption).
 *
 * Pages are stored in the VFS index format but without transformation.
 * Useful for benchmarking or data that doesn't benefit from compression.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_register_passthrough(const char *name, const char *base_dir);

#if defined(TURBOLITE_ENCRYPTION)
/**
 * Register an encrypted + compressed VFS.
 *
 * Pages are compressed with zstd then encrypted with AES-256-GCM.
 * Requires the `encryption` feature at build time.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_register_encrypted(const char *name,
                                 const char *base_dir,
                                 int compression_level,
                                 const char *password);
#endif

#if defined(TURBOLITE_TIERED)
/**
 * Register a tiered S3-backed VFS.
 *
 * The VFS stores data in S3 with a local NVMe cache. Requires the `tiered`
 * feature at build time.
 *
 * # Parameters
 * - `name`: VFS name.
 * - `bucket`: S3 bucket name.
 * - `prefix`: S3 key prefix (e.g. `"databases/tenant-123"`).
 * - `cache_dir`: Local cache directory path.
 * - `endpoint_url`: Custom S3 endpoint (for MinIO/Tigris), or NULL for AWS default.
 * - `region`: AWS region, or NULL for `"auto"`.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_register_tiered(const char *name,
                              const char *bucket,
                              const char *prefix,
                              const char *cache_dir,
                              const char *endpoint_url,
                              const char *region);
#endif

/**
 * Clear all VFS caches (shared file state, in-process locks).
 *
 * Call this when running fresh benchmarks or tests to ensure no stale state.
 */
void turbolite_clear_caches(void);

/**
 * Invalidate cached state for a specific database file.
 *
 * Call after modifying a database file externally (e.g. after compaction).
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_invalidate_cache(const char *path);

/**
 * Open a database using a previously registered VFS.
 *
 * # Parameters
 * - `path`: Database file path.
 * - `vfs_name`: Name of the VFS registered via `turbolite_register_*`.
 *
 * # Returns
 * Opaque handle on success, NULL on error. Must be closed with `turbolite_close`.
 */
struct TurboliteDb *turbolite_open(const char *path, const char *vfs_name);

/**
 * Execute a SQL statement (DDL/DML) that returns no rows.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_exec(struct TurboliteDb *db, const char *sql);

/**
 * Execute a SQL query and return results as a JSON array of objects.
 *
 * Example return: `[{"id":1,"name":"alice"},{"id":2,"name":"bob"}]`
 *
 * # Returns
 * Heap-allocated JSON string on success (caller must free with `turbolite_free_string`),
 * or NULL on error.
 */
char *turbolite_query_json(struct TurboliteDb *db, const char *sql);

/**
 * Free a string returned by `turbolite_query_json`.
 */
void turbolite_free_string(char *s);

/**
 * Close a database connection opened with `turbolite_open`.
 */
void turbolite_close(struct TurboliteDb *db);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TURBOLITE_H */
