/* turbolite — SQLite VFS with compression, encryption, and S3 tiered storage.
 *
 * Auto-generated by cbindgen. Do not edit manually.
 * https://github.com/russellromney/turbolite
 */


#ifndef TURBOLITE_H
#define TURBOLITE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Minimum confidence to fire a prediction.
 */
#define CONFIDENCE_THRESHOLD 0.5

/**
 * Opaque database connection handle.
 */
typedef struct TurboliteDb TurboliteDb;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Get the last error message, or NULL if no error occurred.
 *
 * The returned pointer is valid until the next turbolite_* call on this thread.
 */
const char *turbolite_last_error(void);

/**
 * Get the turbolite version string. Always returns a valid pointer.
 */
const char *turbolite_version(void);

/**
 * Register a local TurboliteVfs (page groups on disk, no S3).
 *
 * This is the recommended way to create a high-performance local SQLite VFS
 * with compressed page groups and manifest-based storage.
 *
 * # Parameters
 * - `name`: VFS name (e.g. `"turbolite"`). Must be unique.
 * - `cache_dir`: Directory where page groups and manifest are stored.
 * - `compression_level`: zstd level 1-22 (3 is a good default).
 *
 * # Returns
 * 0 on success, -1 on error. Call `turbolite_last_error()` for details.
 */
int turbolite_register_local(const char *name, const char *cache_dir, int compression_level);

/**
 * Register a TurboliteVfs from a JSON configuration string.
 *
 * Unified entry point that supports both local and cloud modes. The JSON
 * object is deserialized into a `TurboliteConfig`. Unknown fields are ignored.
 *
 * # Minimal JSON (local mode)
 *
 * ```json
 * { "cache_dir": "/data/mydb" }
 * ```
 *
 * # Cloud mode
 *
 * ```json
 * {
 *   "storage_backend": { "S3": { "bucket": "my-bucket", "prefix": "db/" } },
 *   "cache_dir": "/tmp/cache"
 * }
 * ```
 *
 * # Parameters
 * - `name`: VFS name (e.g. `"turbolite"`). Must be unique.
 * - `config_json`: JSON string with configuration fields.
 *
 * # Returns
 * 0 on success, -1 on error. Call `turbolite_last_error()` for details.
 */
int turbolite_register(const char *name, const char *config_json);

#if defined(TURBOLITE_CLOUD)
/**
 * Register an S3-backed cloud VFS.
 *
 * The VFS stores data in S3 with a local NVMe cache. Requires the `cloud`
 * feature at build time.
 *
 * # Parameters
 * - `name`: VFS name.
 * - `bucket`: S3 bucket name.
 * - `prefix`: S3 key prefix (e.g. `"databases/tenant-123"`).
 * - `cache_dir`: Local cache directory path.
 * - `endpoint_url`: Custom S3 endpoint (for MinIO/Tigris), or NULL for AWS default.
 * - `region`: AWS region, or NULL for `"auto"`.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_register_cloud(const char *name,
                             const char *bucket,
                             const char *prefix,
                             const char *cache_dir,
                             const char *endpoint_url,
                             const char *region);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Backward-compatible alias for `turbolite_register_cloud`.
 */
int turbolite_register_tiered(const char *name,
                              const char *bucket,
                              const char *prefix,
                              const char *cache_dir,
                              const char *endpoint_url,
                              const char *region);
#endif

/**
 * Clear all VFS caches (shared file state, in-process locks).
 *
 * Call this when running fresh benchmarks or tests to ensure no stale state.
 */
void turbolite_clear_caches(void);

/**
 * Invalidate cached state for a specific database file.
 *
 * Call after modifying a database file externally (e.g. after compaction).
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_invalidate_cache(const char *path);

/**
 * Open a database using a previously registered VFS.
 *
 * # Parameters
 * - `path`: Database file path.
 * - `vfs_name`: Name of the VFS registered via `turbolite_register_*`.
 *
 * # Returns
 * Opaque handle on success, NULL on error. Must be closed with `turbolite_close`.
 */
struct TurboliteDb *turbolite_open(const char *path, const char *vfs_name);

/**
 * Execute a SQL statement (DDL/DML) that returns no rows.
 *
 * # Returns
 * 0 on success, -1 on error.
 */
int turbolite_exec(struct TurboliteDb *db, const char *sql);

/**
 * Execute a SQL query and return results as a JSON array of objects.
 *
 * Example return: `[{"id":1,"name":"alice"},{"id":2,"name":"bob"}]`
 *
 * # Returns
 * Heap-allocated JSON string on success (caller must free with `turbolite_free_string`),
 * or NULL on error.
 */
char *turbolite_query_json(struct TurboliteDb *db, const char *sql);

/**
 * Free a string returned by `turbolite_query_json`.
 */
void turbolite_free_string(char *s);

/**
 * Close a database connection opened with `turbolite_open`.
 */
void turbolite_close(struct TurboliteDb *db);

/**
 * Called from C entry point (`sqlite3_turbolite_init` in ext_entry.c).
 * Returns 0 on success, 1 on error. Idempotent: second call is a no-op.
 *
 * Always registers "turbolite" (local TurboliteVfs).
 * If TURBOLITE_BUCKET is set, also registers "turbolite-s3" (tiered VFS).
 * Panics if TURBOLITE_BUCKET is set but tiered VFS creation fails.
 */
int turbolite_ext_register_vfs(void);

#if defined(TURBOLITE_CLOUD)
/**
 * Clear cache. mode: 0 = all, 1 = data only, 2 = interior only (keeps interior + group 0).
 * Returns 0 on success, 1 if no tiered VFS.
 */
int32_t turbolite_bench_clear_cache(int32_t mode);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Reset S3 counters. Returns 0 on success.
 */
int32_t turbolite_bench_reset_s3(void);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Get S3 GET count since last reset.
 */
int64_t turbolite_bench_s3_gets(void);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Get S3 GET bytes since last reset.
 */
int64_t turbolite_bench_s3_bytes(void);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Evict cached data for named trees. tree_names is a comma-separated C string.
 * Returns number of groups evicted, or -1 if no tiered VFS.
 */
int32_t turbolite_evict_tree(const char *tree_names);
#endif

#if !defined(TURBOLITE_CLOUD)
int32_t turbolite_evict_tree(const char *_tree_names);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Return cache info as a JSON C string. Caller must treat as SQLITE_TRANSIENT.
 * Returns null if no tiered VFS.
 *
 * Uses a thread-local buffer to avoid allocation lifetime issues across FFI.
 */
const char *turbolite_cache_info(void);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Warm cache for a planned query. Runs EQP to extract trees, submits groups to prefetch.
 * Returns JSON C string with trees warmed and groups submitted. Null if no tiered VFS.
 * db must be a valid sqlite3 handle, sql must be a valid C string.
 */
const char *turbolite_warm(void *db, const char *sql);
#endif

#if !defined(TURBOLITE_CLOUD)
const char *turbolite_warm(void *_db, const char *_sql);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Evict cached data for trees referenced by a SQL query. Runs EQP, extracts
 * tree names, evicts their groups. Returns groups evicted, or -1 if no VFS.
 */
int32_t turbolite_evict_query(void *db, const char *sql);
#endif

#if !defined(TURBOLITE_CLOUD)
int32_t turbolite_evict_query(void *_db, const char *_sql);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Evict cached sub-chunks by tier. Accepts "data", "index", or "all".
 * Returns number of sub-chunks evicted, or -1 if no tiered VFS.
 */
int32_t turbolite_evict(const char *tier);
#endif

#if !defined(TURBOLITE_CLOUD)
int32_t turbolite_evict(const char *_tier);
#endif

#if !defined(TURBOLITE_CLOUD)
const char *turbolite_cache_info(void);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Full GC: list all S3 objects under prefix, delete orphans not in manifest.
 * Returns number of objects deleted, or -1 if no tiered VFS.
 */
int32_t turbolite_gc(void);
#endif

#if defined(TURBOLITE_CLOUD)
/**
 * Compact B-tree groups: re-walk B-trees, repack groups with >30% dead space.
 * Returns JSON report string (caller must free), or null on error.
 */
const char *turbolite_compact(void);
#endif

#if !defined(TURBOLITE_CLOUD)
const char *turbolite_compact(void);
#endif

#if !defined(TURBOLITE_CLOUD)
int32_t turbolite_gc(void);
#endif

extern int32_t sqlite3_prepare_v2(void *db,
                                  const char *sql,
                                  int32_t nbyte,
                                  void **stmt,
                                  const char **tail);

extern int32_t sqlite3_step(void *stmt);

extern const char *sqlite3_column_text(void *stmt, int32_t col);

extern int32_t sqlite3_finalize(void *stmt);

extern int64_t sqlite3_column_int64(void *stmt, int32_t col);

/**
 * FFI entry point called from C trace callback.
 * Runs EQP, parses, and pushes to global queue.
 *
 * # Safety
 * `db` must be a valid sqlite3 handle. `sql` must be a valid C string.
 */
void turbolite_trace_push_plan(void *db, const char *sql);

/**
 * Phase Jena-d2: discover schema from sqlite_master and push to global cache.
 * Called once per db connection from the trace callback.
 *
 * # Safety
 * `db` must be a valid sqlite3 handle.
 */
void turbolite_discover_schema(void *db);

/**
 * FFI entry point called from C trace profile callback.
 * Signals query completion for between-query eviction.
 */
void turbolite_trace_end_query(void);

/**
 * FFI entry point: `turbolite_config_set(key, value)` SQL function.
 *
 * # Safety
 * `key` and `value` must be valid C strings.
 */
int32_t turbolite_config_set(const char *key, const char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TURBOLITE_H */
