/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A SQLite database connection with transparent compression. */
export declare class Database {
  /**
   * Open a database with transparent zstd compression.
   *
   * @param path - Path to the database file.
   * @param compression - zstd compression level 1-22 (default 3). Pass null for no compression.
   */
  constructor(path: string, compression?: number | undefined | null)
  /** Execute SQL that returns no rows (DDL, INSERT, UPDATE, DELETE). */
  exec(sql: string): void
  /** Execute a SELECT and return rows as an array of objects. */
  query(sql: string): Array<any>
  /** Close the database connection. */
  close(): void
}
