/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for opening a Database. */
export interface DatabaseOptions {
  /** Storage mode: "local" (default) or "s3". */
  mode?: string
  /** Zstd compression level 1-22 (local mode, default 3). Pass null for no compression. */
  compression?: number
  /** S3 bucket name (required when mode = "s3"). */
  bucket?: string
  /** S3 endpoint URL, e.g. for Tigris or MinIO (mode = "s3"). */
  endpoint?: string
  /** S3 key prefix (mode = "s3", default "turbolite"). */
  prefix?: string
  /** Local cache directory (mode = "s3", defaults to db file's parent directory). */
  cacheDir?: string
  /** AWS region (mode = "s3"). */
  region?: string
}
/** A SQLite database connection with transparent compression or S3 tiered storage. */
export declare class Database {
  /**
   * Open a database.
   *
   * @param path - Path to the database file.
   * @param options - Options object. Omit for local compressed mode.
   *   Local mode: `{ compression: 3 }` (zstd level 1-22; omit for no compression).
   *   S3 mode:    `{ mode: "s3", bucket: "my-bucket", endpoint: "..." }`.
   */
  constructor(path: string, options?: DatabaseOptions | undefined | null)
  /** Execute SQL that returns no rows (DDL, INSERT, UPDATE, DELETE). */
  exec(sql: string): void
  /** Execute a SELECT and return rows as an array of objects. */
  query(sql: string): Array<any>
  /** Close the database connection. */
  close(): void
}
